[MT5]
login    = xxx
password = xxx
server   = Exness-MT5Trial8


[TRADING]
; Danh sách symbol, phân cách bằng dấu phẩy
symbols       = XAUUSD, USDJPY, BTCUSD, EURUSD, GBPUSD, USOIL, 
sl_pips       = 0
max_positions = 1

; Lot riêng cho từng symbol (lot_size_SYMBOL)

lot_size_XAUUSD = 0.03
lot_size_BTCUSD = 0.13
lot_size_USOIL  = 0.05

lot_size_EURUSD = 0.2
lot_size_USDJPY = 0.2
lot_size_GBPUSD = 0.2


;lot_size_USDCNH = 0.1

; Lot mặc định nếu symbol không có trong danh sách trên
;lot_size = 0.05

[STRATEGY]
volume_multiplier   = 0.5
body_multiplier     = 0.5
body_multiplier_max = 1.2
entry_window_sec    = 30

; Thân nến T-2 tối thiểu theo từng symbol
min_body_t2_XAUUSD = 2.011000
min_body_t2_BTCUSD = 92.260000
min_body_t2_USDJPY = 0.040000
min_body_t2_EURUSD = 0.000240
min_body_t2_GBPUSD = 0.000280
min_body_t2_USOIL  = 0.058000

;min_body_t2_USDCNH = 0.000610

[SYSTEM]
loop_interval = 5
excel_log     = trades_log.xlsx
